// importing components
import Footer from "@/components/Footer";
import Header from "@/components/Legal/Header";

// importing fonts
import { titleFont } from "@/utils/fonts";

export default function TermsOfSale() {
  return (
    <main>
      <Header />

      <div className="flex flex-col gap-5 min-h-screen w-full px-5 py-[2rem]">
        <h1 className={`text-[3rem] text-center ${titleFont.className}`}>
          Terms of Sale
        </h1>

        <h2 className="text-center">Last Modified: May 23, 2023</h2>

        <div className="flex flex-col gap-5 w-full md:w-3/4 mx-auto">
          <p>
            Sponsorless LLC ("We" or "Sponsorless") operates as a brand
            providing services and products to the outdoor community. Our
            primary goal is to connect brands, communities, and athletes,
            fostering collaborations and opportunities within the industry. Our
            initial product offering consists of a digital membership in the
            form of a non-fungible token (NFT). This NFT, known as the
            "Membership NFT," can be purchased using a credit card with a 3rd
            party provider or through OpenSea.
          </p>

          <p>
            The Membership NFT comes in two tiers: "Founder Member" and "Gold
            Member." Each tier provides access to a range of benefits and
            features, including educational courses, coaching services, event
            access, participation in our athlete accelerator program, custom
            merchandise, and opportunities for athletes to generate income while
            promoting their own brands and sponsors.
          </p>
          <p>
            By purchasing a Membership NFT, you acknowledge that the transaction
            involves the acquisition of goods and does not guarantee the
            provision of future services from Sponsorless. While Sponsorless
            will make reasonable efforts to establish a platform that unlocks
            additional functionality associated with the Membership NFTs,
            ownership of the NFT does not entitle you to vote, receive dividends
            or profits, or hold shares of Sponsorless LLC or any other entity.
            Furthermore, owning a Membership NFT does not grant you the rights
            of a shareholder, partner, joint venturer, or any similar privileges
            related to corporate governance.
          </p>
          <p>
            Sponsorless LLC may offer the opportunity for Membership NFT holders
            to participate in a gamification platform in the future. Sponsorless
            my also offer the opportunity for Membership NFT holders to
            participate in a decentralized autonomous organization (DAO) in the
            future. The features and functionality of any gamification platform
            or DAO established by Sponsorless will be determined solely at the
            discretion of Sponsorless.
          </p>
          <p>
            You understand and accept that the development of Sponsorless LLC's
            business entails significant risks. You acknowledge and assume the
            risk that Sponsorless may encounter obstacles or be unable to fully
            realize its operational plans, including the brand connections,
            affiliate offers, live events, or any other aspects of its
            operations. Additionally, a substantial portion of the funds
            generated by the Membership NFT sale may be retained by Sponsorless
            LLC for lawful business purposes. Purchasing a Membership NFT
            carries the risk of a complete loss of your investment, and no
            refunds will be provided. The creation and delivery of Membership
            NFTs are provided to purchasers "as-is" and at their sole risk.
          </p>
          <p>
            Your purchase of a Membership NFT is subject to the Terms of Sale
            governed by New York law, without considering conflict of laws
            principles. Any disputes between you or your successors/assigns and
            Sponsorless arising directly or indirectly from these Terms of Sale
            or the NFTs shall be exclusively resolved through final and binding
            arbitration in the State of New York, in New York City, in
            accordance with the Rules of Arbitration of the American Arbitration
            Association.
          </p>
          <p>
            CLASS ACTION WAIVER: TO THE FULLEST EXTENT PERMITTED BY APPLICABLE
            LAW, ALL CLAIMS MUST BE BROUGHT IN AN INDIVIDUAL CAPACITY AND NOT AS
            A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS, COLLECTIVE
            ACTION, OR REPRESENTATIVE PROCEEDING. THE ARBITRATOR MAY NOT
            CONSOLIDATE MORE THAN ONE PERSON'S CLAIMS OR ENGAGE IN ANY FORM OF
            CLASS ARBITRATION. BY AGREEING TO THESE TERMS, YOU AND SPONSORLESS
            LLC ACKNOWLEDGE THAT YOU ARE WAIVING THE RIGHT TO A TRIAL BY JUDGE
            OR JURY IN A PUBLIC FORUM AND THE RIGHT TO PARTICIPATE IN A CLASS
            ACTION.
          </p>
          <p>
            Except in cases of Sponsorless LLC's fraud or willful default and as
            required by non-waivable provisions of applicable law, Sponsorless
            LLC shall not be liable to you or any other person for any losses or
            damages, whether arising in contract, tort, or otherwise, resulting
            from the sale of Membership NFTs.
          </p>
          <p>
            All purchases of Membership NFTs are considered final and
            nonrefundable.
          </p>
          <p>
            If you have any questions, please contact Sponsorless LLC at
            contact@sponsorless.com.
          </p>
        </div>
      </div>

      <Footer />
    </main>
  );
}
